  name: solaredge_monitor
  description: "Application de monitoring SolarEdge avec intégration IA."
  publish_to: 'none'
  version: 1.0.0+1

  environment:
    sdk: '>=3.0.0 <4.0.0' # Version de SDK mise à jour pour compatibilité

  dependencies:
    flutter:
      sdk: flutter
    flutter_localizations:
      sdk: flutter
    cupertino_icons: ^1.0.8
    share_plus: ^11.0.0
    timezone: ^0.10.0 # Maintenir une version stable si besoin
    xml: ^6.5.0


    # État et architecture
    provider: ^6.1.1
    get_it: ^8.0.3

    firebase_core: ^3.2.0
    firebase_auth: ^5.1.2
    firebase_messaging: ^15.0.2
    google_sign_in: ^6.1.4
    
    cloud_firestore: ^5.0.0 # Ajout pour Firestore

    # API et réseau
    http: ^1.2.0
    dio: ^5.4.1
    connectivity_plus: ^6.1.4

    # Stockage local
    shared_preferences: ^2.2.2
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    path_provider: ^2.1.5 # Déjà présent

    # UI et graphiques
    fl_chart: ^0.71.0
    flutter_svg: ^2.0.10+1
    lottie: ^3.1.0
    google_fonts: ^6.1.0
    flutter_animate: ^4.5.0
    cached_network_image: ^3.3.1

    # Intégration IA
    google_generative_ai: ^0.4.7

    # Utilitaires
    intl: ^0.19.0
    flutter_local_notifications: ^19.1.0
    url_launcher: ^6.2.5
    geocoding: ^4.0.0
    geolocator: ^14.0.1 # Rétrogradation pour compatibilité SDK Flutter < 3.10
    workmanager: ^0.7.0
    android_alarm_manager_plus: ^4.0.7
    permission_handler: ^12.0.0+1
    # *** AJOUT ***
    flutter_timezone: ^4.1.1 # Version compatible
    uuid: ^4.5.1
    time_machine: ^0.9.17

  dev_dependencies:
    flutter_test:
      sdk: flutter
    mockito: ^5.4.4 # Maintenir pour tests
    flutter_lints: ^5.0.0 # Utiliser une version plus récente si possible
    hive_generator: ^2.0.1
    build_runner: ^2.4.8

  flutter:
    uses-material-design: true

    assets:
      - assets/images/
      - assets/animations/

    fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins-Medium.ttf
            weight: 500
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 700
